SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [hub_serviceinc].[salesforce_workordernumber_proc] 
@pipeline_name [VARCHAR](100),
@pipeline_run_id [VARCHAR](100),
@pipeline_trigger_name [VARCHAR](100),
@pipeline_trigger_id [VARCHAR](100),
@pipeline_trigger_type [VARCHAR](100),
@pipeline_trigger_date_time_utc [DATETIME2],
@lastest_partition [varchar](20),
@elt_table_config_id [varchar](20) AS 

BEGIN TRY

DECLARE @trans_lastest_partition [varchar](20)
    SET    @trans_lastest_partition =
    ( SELECT    MAX ( ISNULL([ingest_partition],'1900-00-00-00') )
    FROM  [trans_serviceinc_salesforce].[workordernumbernumber] )

MERGE INTO [hub_serviceinc].[salesforce_workordernumber] AS tgt
USING (
        SELECT
        CAST( [AccountId] as nvarchar(max)) as [AccountId],
        CAST( [Alt_Work_Site_Flag__c] as bit) as [Alt_Work_Site_Flag__c],
        CAST( [AssetId] as nvarchar(max)) as [AssetId],
        CAST( [BusinessHoursId] as nvarchar(max)) as [BusinessHoursId],
        CAST( [CaseId] as nvarchar(max)) as [CaseId],
        CAST( [Case_CaseNumber] as nvarchar(max)) as [Case_CaseNumber],
        CAST( [City] as nvarchar(max)) as [City],
        CAST( [Complete_Date_Local__c] as nvarchar(max)) as [Complete_Date_Local__c],
        CAST( [Complete_Date__c]as datetime2(7)) as [Complete_Date__c],
        CAST( [Config_Details__c] as nvarchar(max)) as [Config_Details__c],
        CAST( [ContactId] as nvarchar(max)) as [ContactId],
        CAST( [Country] as nvarchar(max)) as [Country],
        CAST( [CreatedById] as nvarchar(max)) as [CreatedById],
        CAST( [CreatedDate]as datetime2(7)) as [CreatedDate],
        CAST( [CurrencyIsoCode] as nvarchar(max)) as [CurrencyIsoCode],
        CAST( [Customer_External_Id__c] as nvarchar(max)) as [Customer_External_Id__c],
        CAST( [Customer_Ticket_Number__c] as nvarchar(max)) as [Customer_Ticket_Number__c],
        CAST( [Description] as nvarchar(max)) as [Description],
        CAST( [Discount] as numeric(38, 18)) as [Discount],
        CAST( [Dispatch_Case_Status_ES__c] as nvarchar(max)) as [Dispatch_Case_Status_ES__c],
        CAST( [Dispatch_Comments_ES__c] as nvarchar(max)) as [Dispatch_Comments_ES__c],
        CAST( [Dispatch_Request_Error_Details__c] as nvarchar(max)) as [Dispatch_Request_Error_Details__c],
        CAST( [Dispatch_Ticket_Status_ES__c] as nvarchar(max)) as [Dispatch_Ticket_Status_ES__c],
        CAST( [Dispatch_WO_Number__c] as nvarchar(max)) as [Dispatch_WO_Number__c],
        CAST( [Duration] as numeric(38, 18)) as [Duration],
        CAST( [DurationInMinutes] as numeric(38, 18)) as [DurationInMinutes],
        CAST( [DurationType] as nvarchar(max)) as [DurationType],
        CAST( [EndDate]as datetime2(7)) as [EndDate],
        CAST( [EntitlementId] as nvarchar(max)) as [EntitlementId],
        CAST( [Error_Details__c] as nvarchar(max)) as [Error_Details__c],
        CAST( [FaultCode__c] as nvarchar(max)) as [FaultCode__c],
        CAST( [FaultDescription__c] as nvarchar(max)) as [FaultDescription__c],
        CAST( [Fault__c] as nvarchar(max)) as [Fault__c],
        CAST( [GeocodeAccuracy] as nvarchar(max)) as [GeocodeAccuracy],
        CAST( [GrandTotal] as numeric(38, 18)) as [GrandTotal],
        CAST( [Id] as nvarchar(max)) as [Id],
        CAST( [Inbound_SN__c] as nvarchar(max)) as [Inbound_SN__c],
        CAST( [Inbound_Tracking__c] as nvarchar(max)) as [Inbound_Tracking__c],
        CAST( [IsClosed] as bit) as [IsClosed],
        CAST( [IsDeleted] as bit) as [IsDeleted],
        CAST( [IsStopped] as bit) as [IsStopped],
        CAST( [LastModifiedById] as nvarchar(max)) as [LastModifiedById],
        CAST( [LastModifiedDate]as datetime2(7)) as [LastModifiedDate],
        CAST( [LastReferencedDate]as datetime2(7)) as [LastReferencedDate],
        CAST( [LastViewedDate]as datetime2(7)) as [LastViewedDate],
        CAST( [Latitude] as numeric(38, 18)) as [Latitude],
        CAST( [LineItemCount] as int) as [LineItemCount],
        CAST( [Longitude] as numeric(38, 18)) as [Longitude],
        CAST( [MilestoneStatus] as nvarchar(max)) as [MilestoneStatus],
        CAST( [Owner_Ticket_Id__c] as nvarchar(max)) as [Owner_Ticket_Id__c],
        CAST( [Outbound_SN__c] as nvarchar(max)) as [Outbound_SN__c],
        CAST( [Out_of_Scope_Reason__c] as nvarchar(max)) as [Out_of_Scope_Reason__c],
        CAST( [Out_of_Scope__c] as bit) as [Out_of_Scope__c],
        CAST( [OwnerId] as nvarchar(max)) as [OwnerId],
        CAST( [ParentworkordernumberId] as nvarchar(max)) as [ParentworkordernumberId],
        CAST( [Part_On_Site_Actual_Local__c] as nvarchar(max)) as [Part_On_Site_Actual_Local__c],
        CAST( [Part_On_Site_Actual__c]as datetime2(7)) as [Part_On_Site_Actual__c],
        CAST( [Part_On_Site_ETA_Local__c] as nvarchar(max)) as [Part_On_Site_ETA_Local__c],
        CAST( [Part_On_Site_ETA__c]as datetime2(7)) as [Part_On_Site_ETA__c],
        CAST( [PID__c] as nvarchar(max)) as [PID__c],
        CAST( [PostalCode] as nvarchar(max)) as [PostalCode],
        CAST( [Pricebook2Id] as nvarchar(max)) as [Pricebook2Id],
        CAST( [Priority] as nvarchar(max)) as [Priority],
        CAST( [Priority_Type__c] as numeric(38, 18)) as [Priority_Type__c],
        CAST( [Receipt_Date_Local__c] as nvarchar(max)) as [Receipt_Date_Local__c],
        CAST( [Receipt_Date__c]as datetime2(7)) as [Receipt_Date__c],
        CAST( [Request_Type_Mapping__c] as nvarchar(max)) as [Request_Type_Mapping__c],
        CAST( [Request_Type__c] as nvarchar(max)) as [Request_Type__c],
        CAST( [Return_Tracking_Number__c] as nvarchar(max)) as [Return_Tracking_Number__c],
        CAST( [RMA_Id__c] as nvarchar(max)) as [RMA_Id__c],
        CAST( [RootworkordernumberId] as nvarchar(max)) as [RootworkordernumberId],
        CAST( [Serialized_Asset_Id__c] as nvarchar(max)) as [Serialized_Asset_Id__c],
        CAST( [Serial_Number__c] as nvarchar(max)) as [Serial_Number__c],
        CAST( [ServiceAppointmentCount] as int) as [ServiceAppointmentCount],
        CAST( [ServiceContractId] as nvarchar(max)) as [ServiceContractId],
        CAST( [Service_Level_Id__c] as nvarchar(max)) as [Service_Level_Id__c],
        CAST( [Service_Level_Name__c] as nvarchar(max)) as [Service_Level_Name__c],
        CAST( [Service_Level_Response__c] as nvarchar(max)) as [Service_Level_Response__c],
        CAST( [Service_Level_Type__c] as nvarchar(max)) as [Service_Level_Type__c],
        CAST( [Shipment_Method__c] as nvarchar(max)) as [Shipment_Method__c],
        CAST( [Ship_Date_Local__c] as nvarchar(max)) as [Ship_Date_Local__c],
        CAST( [Ship_Date__c]as datetime2(7)) as [Ship_Date__c],
        CAST( [Site_Id__c] as nvarchar(max)) as [Site_Id__c],
        CAST( [SlaExitDate]as datetime2(7)) as [SlaExitDate],
        CAST( [SlaStartDate]as datetime2(7)) as [SlaStartDate],
        CAST( [SN_Override_Flag__c] as bit) as [SN_Override_Flag__c],
        CAST( [SN_Override__c] as nvarchar(max)) as [SN_Override__c],
        CAST( [Solution_Set_HW_Role_Relation__c] as nvarchar(max)) as [Solution_Set_HW_Role_Relation__c],
        CAST( [StartDate]as datetime2(7)) as [StartDate],
        CAST( [State] as nvarchar(max)) as [State],
        CAST( [Status] as nvarchar(max)) as [Status],
        CAST( [StatusCategory] as nvarchar(max)) as [StatusCategory],
        CAST( [StopStartDate]as datetime2(7)) as [StopStartDate],
        CAST( [Street] as nvarchar(max)) as [Street],
        CAST( [Street_Line_2__c] as nvarchar(max)) as [Street_Line_2__c],
        CAST( [Subject] as nvarchar(max)) as [Subject],
        CAST( [Subtotal] as numeric(38, 18)) as [Subtotal],
        CAST( [Support_Class_Failure_Reason_Relation__c] as nvarchar(max)) as [Support_Class_Failure_Reason_Relation__c],
        CAST( [SystemModstamp]as datetime2(7)) as [SystemModstamp],
        CAST( [Tax] as numeric(38, 18)) as [Tax],
        CAST( [Tech_On_Site_Actual_Local__c] as nvarchar(max)) as [Tech_On_Site_Actual_Local__c],
        CAST( [Tech_On_Site_Actual__c]as datetime2(7)) as [Tech_On_Site_Actual__c],
        CAST( [Tech_On_Site_ETA_Local__c] as nvarchar(max)) as [Tech_On_Site_ETA_Local__c],
        CAST( [Tech_On_Site_ETA__c]as datetime2(7)) as [Tech_On_Site_ETA__c],
        CAST( [TotalPrice] as numeric(38, 18)) as [TotalPrice],
        CAST( [Tracking_Number__c] as nvarchar(max)) as [Tracking_Number__c],
        CAST( [workordernumberNumber] as nvarchar(max)) as [workordernumberNumber],
        CAST( 0 AS INT) AS [adls_extract_ind],
        CAST(@pipeline_name AS [varchar](100)) AS [pipeline_name] ,
        CAST(@pipeline_run_id AS [varchar](100)) AS [pipeline_run_id],
        CAST(@pipeline_trigger_name AS [varchar](100)) AS [pipeline_trigger_name],
        CAST(@pipeline_trigger_id AS [varchar](100)) AS [pipeline_trigger_id],
        CAST(@pipeline_trigger_type AS [varchar](100)) AS [pipeline_trigger_type],
        CAST(@pipeline_trigger_date_time_utc AS [datetime2](7)) AS [pipeline_trigger_date_time_utc],
        CAST(GETDATE() AS [datetime2](7)) AS [hub_load_date_time_utc],
        CAST([adle_transaction_code] AS CHAR(1)) as adle_transaction_code,
         CAST([hash_key] as VARBINARY(32)) as [hash_key]
            FROM [trans_serviceinc_salesforce_cpq].[workordernumber]
            WHERE ISNULL(ingest_partition, '1900-00-00-00') > @lastest_partition
            AND [adle_transaction_code] <> 'D'
) AS src ON (src.[hash_key] = tgt.[hash_key])

WHEN MATCHED THEN

UPDATE
SET
        tgt.[AccountId] = src.[AccountId],
        tgt.[Alt_Work_Site_Flag__c] = src.[Alt_Work_Site_Flag__c],
        tgt.[AssetId] = src.[AssetId],
        tgt.[BusinessHoursId] = src.[BusinessHoursId],
        tgt.[CaseId] = src.[CaseId],
        tgt.[Case_CaseNumber] = src.[Case_CaseNumber],
        tgt.[City] = src.[City],
        tgt.[Complete_Date_Local__c] = src.[Complete_Date_Local__c],
        tgt.[Complete_Date__c] = src.[Complete_Date__c],
        tgt.[Config_Details__c] = src.[Config_Details__c],
        tgt.[ContactId] = src.[ContactId],
        tgt.[Country] = src.[Country],
        tgt.[CreatedById] = src.[CreatedById],
        tgt.[CreatedDate] = src.[CreatedDate],
        tgt.[CurrencyIsoCode] = src.[CurrencyIsoCode],
        tgt.[Customer_External_Id__c] = src.[Customer_External_Id__c],
        tgt.[Customer_Ticket_Number__c] = src.[Customer_Ticket_Number__c],
        tgt.[Description] = src.[Description],
        tgt.[Discount] = src.[Discount],
        tgt.[Dispatch_Case_Status_ES__c] = src.[Dispatch_Case_Status_ES__c],
        tgt.[Dispatch_Comments_ES__c] = src.[Dispatch_Comments_ES__c],
        tgt.[Dispatch_Request_Error_Details__c] = src.[Dispatch_Request_Error_Details__c],
        tgt.[Dispatch_Ticket_Status_ES__c] = src.[Dispatch_Ticket_Status_ES__c],
        tgt.[Dispatch_WO_Number__c] = src.[Dispatch_WO_Number__c],
        tgt.[Duration] = src.[Duration],
        tgt.[DurationInMinutes] = src.[DurationInMinutes],
        tgt.[DurationType] = src.[DurationType],
        tgt.[EndDate] = src.[EndDate],
        tgt.[EntitlementId] = src.[EntitlementId],
        tgt.[Error_Details__c] = src.[Error_Details__c],
        tgt.[FaultCode__c] = src.[FaultCode__c],
        tgt.[FaultDescription__c] = src.[FaultDescription__c],
        tgt.[Fault__c] = src.[Fault__c],
        tgt.[GeocodeAccuracy] = src.[GeocodeAccuracy],
        tgt.[GrandTotal] = src.[GrandTotal],
        tgt.[Id] = src.[Id],
        tgt.[Inbound_SN__c] = src.[Inbound_SN__c],
        tgt.[Inbound_Tracking__c] = src.[Inbound_Tracking__c],
        tgt.[IsClosed] = src.[IsClosed],
        tgt.[IsDeleted] = src.[IsDeleted],
        tgt.[IsStopped] = src.[IsStopped],
        tgt.[LastModifiedById] = src.[LastModifiedById],
        tgt.[LastModifiedDate] = src.[LastModifiedDate],
        tgt.[LastReferencedDate] = src.[LastReferencedDate],
        tgt.[LastViewedDate] = src.[LastViewedDate],
        tgt.[Latitude] = src.[Latitude],
        tgt.[LineItemCount] = src.[LineItemCount],
        tgt.[Longitude] = src.[Longitude],
        tgt.[MilestoneStatus] = src.[MilestoneStatus],
        tgt.[Owner_Ticket_Id__c] = src.[Owner_Ticket_Id__c],
        tgt.[Outbound_SN__c] = src.[Outbound_SN__c],
        tgt.[Out_of_Scope_Reason__c] = src.[Out_of_Scope_Reason__c],
        tgt.[Out_of_Scope__c] = src.[Out_of_Scope__c],
        tgt.[OwnerId] = src.[OwnerId],
        tgt.[ParentworkordernumberId] = src.[ParentworkordernumberId],
        tgt.[Part_On_Site_Actual_Local__c] = src.[Part_On_Site_Actual_Local__c],
        tgt.[Part_On_Site_Actual__c] = src.[Part_On_Site_Actual__c],
        tgt.[Part_On_Site_ETA_Local__c] = src.[Part_On_Site_ETA_Local__c],
        tgt.[Part_On_Site_ETA__c] = src.[Part_On_Site_ETA__c],
        tgt.[PID__c] = src.[PID__c],
        tgt.[PostalCode] = src.[PostalCode],
        tgt.[Pricebook2Id] = src.[Pricebook2Id],
        tgt.[Priority] = src.[Priority],
        tgt.[Priority_Type__c] = src.[Priority_Type__c],
        tgt.[Receipt_Date_Local__c] = src.[Receipt_Date_Local__c],
        tgt.[Receipt_Date__c] = src.[Receipt_Date__c],
        tgt.[Request_Type_Mapping__c] = src.[Request_Type_Mapping__c],
        tgt.[Request_Type__c] = src.[Request_Type__c],
        tgt.[Return_Tracking_Number__c] = src.[Return_Tracking_Number__c],
        tgt.[RMA_Id__c] = src.[RMA_Id__c],
        tgt.[RootworkordernumberId] = src.[RootworkordernumberId],
        tgt.[Serialized_Asset_Id__c] = src.[Serialized_Asset_Id__c],
        tgt.[Serial_Number__c] = src.[Serial_Number__c],
        tgt.[ServiceAppointmentCount] = src.[ServiceAppointmentCount],
        tgt.[ServiceContractId] = src.[ServiceContractId],
        tgt.[Service_Level_Id__c] = src.[Service_Level_Id__c],
        tgt.[Service_Level_Name__c] = src.[Service_Level_Name__c],
        tgt.[Service_Level_Response__c] = src.[Service_Level_Response__c],
        tgt.[Service_Level_Type__c] = src.[Service_Level_Type__c],
        tgt.[Shipment_Method__c] = src.[Shipment_Method__c],
        tgt.[Ship_Date_Local__c] = src.[Ship_Date_Local__c],
        tgt.[Ship_Date__c] = src.[Ship_Date__c],
        tgt.[Site_Id__c] = src.[Site_Id__c],
        tgt.[SlaExitDate] = src.[SlaExitDate],
        tgt.[SlaStartDate] = src.[SlaStartDate],
        tgt.[SN_Override_Flag__c] = src.[SN_Override_Flag__c],
        tgt.[SN_Override__c] = src.[SN_Override__c],
        tgt.[Solution_Set_HW_Role_Relation__c] = src.[Solution_Set_HW_Role_Relation__c],
        tgt.[StartDate] = src.[StartDate],
        tgt.[State] = src.[State],
        tgt.[Status] = src.[Status],
        tgt.[StatusCategory] = src.[StatusCategory],
        tgt.[StopStartDate] = src.[StopStartDate],
        tgt.[Street] = src.[Street],
        tgt.[Street_Line_2__c] = src.[Street_Line_2__c],
        tgt.[Subject] = src.[Subject],
        tgt.[Subtotal] = src.[Subtotal],
        tgt.[Support_Class_Failure_Reason_Relation__c] = src.[Support_Class_Failure_Reason_Relation__c],
        tgt.[SystemModstamp] = src.[SystemModstamp],
        tgt.[Tax] = src.[Tax],
        tgt.[Tech_On_Site_Actual_Local__c] = src.[Tech_On_Site_Actual_Local__c],
        tgt.[Tech_On_Site_Actual__c] = src.[Tech_On_Site_Actual__c],
        tgt.[Tech_On_Site_ETA_Local__c] = src.[Tech_On_Site_ETA_Local__c],
        tgt.[Tech_On_Site_ETA__c] = src.[Tech_On_Site_ETA__c],
        tgt.[TotalPrice] = src.[TotalPrice],
        tgt.[Tracking_Number__c] = src.[Tracking_Number__c],
        tgt.[workordernumberNumber] = src.[workordernumberNumber],
        tgt.[adls_extract_ind] = 0,
        tgt.[hub_load_date_time_utc] = GETDATE(),
        tgt.[adle_transaction_code] = 'U',
        tgt.[pipeline_name] = @pipeline_name,
        tgt.[pipeline_run_id] = @pipeline_run_id,
        tgt.[pipeline_trigger_name] = @pipeline_trigger_name,
        tgt.[pipeline_trigger_id] = @pipeline_trigger_id,
        tgt.[pipeline_trigger_type] = @pipeline_trigger_type,
        tgt.[pipeline_trigger_date_time_utc] = @pipeline_trigger_date_time_utc

WHEN NOT MATCHED THEN
INSERT (
        [AccountId],
        [Alt_Work_Site_Flag__c],
        [AssetId],
        [BusinessHoursId],
        [CaseId],
        [Case_CaseNumber],
        [City],
        [Complete_Date_Local__c],
        [Complete_Date__c],
        [Config_Details__c],
        [ContactId],
        [Country],
        [CreatedById],
        [CreatedDate],
        [CurrencyIsoCode],
        [Customer_External_Id__c],
        [Customer_Ticket_Number__c],
        [Description],
        [Discount],
        [Dispatch_Case_Status_ES__c],
        [Dispatch_Comments_ES__c],
        [Dispatch_Request_Error_Details__c],
        [Dispatch_Ticket_Status_ES__c],
        [Dispatch_WO_Number__c],
        [Duration],
        [DurationInMinutes],
        [DurationType],
        [EndDate],
        [EntitlementId],
        [Error_Details__c],
        [FaultCode__c],
        [FaultDescription__c],
        [Fault__c],
        [GeocodeAccuracy],
        [GrandTotal],
        [Id],
        [Inbound_SN__c],
        [Inbound_Tracking__c],
        [IsClosed],
        [IsDeleted],
        [IsStopped],
        [LastModifiedById],
        [LastModifiedDate],
        [LastReferencedDate],
        [LastViewedDate],
        [Latitude],
        [LineItemCount],
        [Longitude],
        [MilestoneStatus],
        [Owner_Ticket_Id__c],
        [Outbound_SN__c],
        [Out_of_Scope_Reason__c],
        [Out_of_Scope__c],
        [OwnerId],
        [ParentworkordernumberId],
        [Part_On_Site_Actual_Local__c],
        [Part_On_Site_Actual__c],
        [Part_On_Site_ETA_Local__c],
        [Part_On_Site_ETA__c],
        [PID__c],
        [PostalCode],
        [Pricebook2Id],
        [Priority],
        [Priority_Type__c],
        [Receipt_Date_Local__c],
        [Receipt_Date__c],
        [Request_Type_Mapping__c],
        [Request_Type__c],
        [Return_Tracking_Number__c],
        [RMA_Id__c],
        [RootworkordernumberId],
        [Serialized_Asset_Id__c],
        [Serial_Number__c],
        [ServiceAppointmentCount],
        [ServiceContractId],
        [Service_Level_Id__c],
        [Service_Level_Name__c],
        [Service_Level_Response__c],
        [Service_Level_Type__c],
        [Shipment_Method__c],
        [Ship_Date_Local__c],
        [Ship_Date__c],
        [Site_Id__c],
        [SlaExitDate],
        [SlaStartDate],
        [SN_Override_Flag__c],
        [SN_Override__c],
        [Solution_Set_HW_Role_Relation__c],
        [StartDate],
        [State],
        [Status],
        [StatusCategory],
        [StopStartDate],
        [Street],
        [Street_Line_2__c],
        [Subject],
        [Subtotal],
        [Support_Class_Failure_Reason_Relation__c],
        [SystemModstamp],
        [Tax],
        [Tech_On_Site_Actual_Local__c],
        [Tech_On_Site_Actual__c],
        [Tech_On_Site_ETA_Local__c],
        [Tech_On_Site_ETA__c],
        [TotalPrice],
        [Tracking_Number__c],
        [workordernumberNumber],
            [hash_key],     
            [adls_extract_ind],
            [hub_load_date_time_utc],
            [adle_transaction_code] ,
            [pipeline_name] ,
            [pipeline_run_id] ,
            [pipeline_trigger_name],
            [pipeline_trigger_id] ,
            [pipeline_trigger_type],
            [pipeline_trigger_date_time_utc]
        )
        VALUES
        (   [src].[AccountId],
        [src].[Alt_Work_Site_Flag__c],
        [src].[AssetId],
        [src].[BusinessHoursId],
        [src].[CaseId],
        [src].[Case_CaseNumber],
        [src].[City],
        [src].[Complete_Date_Local__c],
        [src].[Complete_Date__c],
        [src].[Config_Details__c],
        [src].[ContactId],
        [src].[Country],
        [src].[CreatedById],
        [src].[CreatedDate],
        [src].[CurrencyIsoCode],
        [src].[Customer_External_Id__c],
        [src].[Customer_Ticket_Number__c],
        [src].[Description],
        [src].[Discount],
        [src].[Dispatch_Case_Status_ES__c],
        [src].[Dispatch_Comments_ES__c],
        [src].[Dispatch_Request_Error_Details__c],
        [src].[Dispatch_Ticket_Status_ES__c],
        [src].[Dispatch_WO_Number__c],
        [src].[Duration],
        [src].[DurationInMinutes],
        [src].[DurationType],
        [src].[EndDate],
        [src].[EntitlementId],
        [src].[Error_Details__c],
        [src].[FaultCode__c],
        [src].[FaultDescription__c],
        [src].[Fault__c],
        [src].[GeocodeAccuracy],
        [src].[GrandTotal],
        [src].[Id],
        [src].[Inbound_SN__c],
        [src].[Inbound_Tracking__c],
        [src].[IsClosed],
        [src].[IsDeleted],
        [src].[IsStopped],
        [src].[LastModifiedById],
        [src].[LastModifiedDate],
        [src].[LastReferencedDate],
        [src].[LastViewedDate],
        [src].[Latitude],
        [src].[LineItemCount],
        [src].[Longitude],
        [src].[MilestoneStatus],
        [src].[Owner_Ticket_Id__c],
        [src].[Outbound_SN__c],
        [src].[Out_of_Scope_Reason__c],
        [src].[Out_of_Scope__c],
        [src].[OwnerId],
        [src].[ParentworkordernumberId],
        [src].[Part_On_Site_Actual_Local__c],
        [src].[Part_On_Site_Actual__c],
        [src].[Part_On_Site_ETA_Local__c],
        [src].[Part_On_Site_ETA__c],
        [src].[PID__c],
        [src].[PostalCode],
        [src].[Pricebook2Id],
        [src].[Priority],
        [src].[Priority_Type__c],
        [src].[Receipt_Date_Local__c],
        [src].[Receipt_Date__c],
        [src].[Request_Type_Mapping__c],
        [src].[Request_Type__c],
        [src].[Return_Tracking_Number__c],
        [src].[RMA_Id__c],
        [src].[RootworkordernumberId],
        [src].[Serialized_Asset_Id__c],
        [src].[Serial_Number__c],
        [src].[ServiceAppointmentCount],
        [src].[ServiceContractId],
        [src].[Service_Level_Id__c],
        [src].[Service_Level_Name__c],
        [src].[Service_Level_Response__c],
        [src].[Service_Level_Type__c],
        [src].[Shipment_Method__c],
        [src].[Ship_Date_Local__c],
        [src].[Ship_Date__c],
        [src].[Site_Id__c],
        [src].[SlaExitDate],
        [src].[SlaStartDate],
        [src].[SN_Override_Flag__c],
        [src].[SN_Override__c],
        [src].[Solution_Set_HW_Role_Relation__c],
        [src].[StartDate],
        [src].[State],
        [src].[Status],
        [src].[StatusCategory],
        [src].[StopStartDate],
        [src].[Street],
        [src].[Street_Line_2__c],
        [src].[Subject],
        [src].[Subtotal],
        [src].[Support_Class_Failure_Reason_Relation__c],
        [src].[SystemModstamp],
        [src].[Tax],
        [src].[Tech_On_Site_Actual_Local__c],
        [src].[Tech_On_Site_Actual__c],
        [src].[Tech_On_Site_ETA_Local__c],
        [src].[Tech_On_Site_ETA__c],
        [src].[TotalPrice],
        [src].[Tracking_Number__c],
        [src].[workordernumberNumber],
        [src].[hash_key],
        0,
        GETDATE(),
        'I',
@pipeline_name,
@pipeline_run_id,
@pipeline_trigger_name,
@pipeline_trigger_id,
@pipeline_trigger_type,
@pipeline_trigger_date_time_utc
);


    EXEC    [adle_platform_orchestration].[elt_table_load_history_proc]
    'trans2hub', @elt_table_config_id, @trans_lastest_partition, 'Success', '';
    END TRY

BEGIN CATCH
    DECLARE @db_name VARCHAR(200),
            @schema_name VARCHAR(200),
            @error_nbr INT,
            @error_severity INT,
            @error_state INT,
            @stored_proc_name VARCHAR(200),
            @error_message VARCHAR(8000),
            @created_date_time DATETIME2
    SET @db_name=DB_NAME()
    SET @schema_name=SUBSTRING (@pipeline_name, CHARINDEX('2', @pipeline_name) + 1, LEN(@pipeline_name) - CHARINDEX('2', @pipeline_name) - 3 )
    SET @error_nbr=ERROR_NUMBER()
    SET @error_severity=ERROR_SEVERITY()
    SET @error_state=ERROR_STATE()
    SET @stored_proc_name=ERROR_PROCEDURE()
    SET @error_message=ERROR_MESSAGE()
    SET @created_date_time=GETDATE()
    EXECUTE [adle_platform_orchestration].[elt_error_log_proc]
        @db_name,
        'ERROR',
        @schema_name,
        @error_nbr,
        @error_severity,
        @error_state,
        @stored_proc_name,
        'PROC',
        @error_message,
        @created_date_time,
        @pipeline_name,
        @pipeline_run_id,
        @pipeline_trigger_name,
        @pipeline_trigger_id,
        @pipeline_trigger_type,
        @pipeline_trigger_date_time_utc
        ;
    THROW;
END CATCH
;
GO
